apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  labels:
    {{- include "spring.labels" . | nindent 4 }}

data:
  dbname: "{{ .Values.database.prod.dbname }}"
  dbtable: "{{ .Values.database.prod.dbtable }}"
  image: "{{ .Values.pods.image }}"
  drink: {{ .Values.food.drink | upper }}
  eat: {{ .Values.food.eat | trunc 13 | upper | quote }}
  